# Generated by Django 4.1.3 on 2022-11-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.BigIntegerField()),
                ("dob", models.DateField()),
                ("image", models.ImageField(upload_to="img/")),
            ],
            options={
                "db_table": "admin_reg",
            },
        ),
        migrations.CreateModel(
            name="StudentReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.BigIntegerField()),
                ("dob", models.DateField()),
                ("image", models.ImageField(upload_to="img/")),
            ],
            options={
                "db_table": "student_reg",
            },
        ),
    ]
