# Generated by Django 4.1.3 on 2022-11-01 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminreg",
            name="password",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentreg",
            name="password",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
