# Generated by Django 4.1.3 on 2022-11-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_adminreg_password_studentreg_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminreg",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentreg",
            name="username",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
